apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
                key: PGDATA

            - configMapRef:
                name: postgres-config
                key: POSTGRES_PORT

            - configMapRef:
                name: postgres-config
                key: POSTGRES_USER
            - configMapRef:
                name: postgres-config
                key: POSTGRES_PASSWORD

            - configMapRef:
                name: postgres-config
                key: 1
            - secretRef:
                name: postgres-secret
                key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pvc-nfs
