apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gb5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:10.13
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgre-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: PGDATA
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: pgdata
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: pvc-nfs
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pvc-nfs
        persistentVolumeClaim:
          claimName: pvc-nfs
