apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gb5
  labels:
    app: postgres
data:
  postgres_db: testdatabase
  postgres_user: testuser
  pgdata: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  namespace: gb5
  labels:
    app: postgres
data:
  redmine_db_postgres: database
  redmine_db_username: ${postgres_user}
  redmine_db_database: ${postgres_db}
